# Задание 1
Для датафрейма log из материалов занятия создайте столбец source_type по следующим правилам:

если источник traffic_source равен yandex или google, то в source_type ставится organic
для источников paid и email из России - ставим ad
для источников paid и email не из России - ставим other
все остальные варианты берем из traffic_source без изменений

In [1]:
import pandas as pd
logs = pd.read_csv('/Users/maksim/Netology/material/visit_log.csv', sep = ';')

In [2]:
logs.head()

,timestamp,visit_id,url,region,user_id,traffic_source
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex

In [3]:
def source_type_func (row):
    if (row['traffic_source'] == 'yandex') | (row['traffic_source'] == 'google'):
        return 'organic'
    elif (row['traffic_source'] == 'paid') & (row['region'] == 'Russia'):
        return 'ad'
    elif (row['traffic_source'] == 'email') & (row['region'] == 'Russia'):
        return 'ad'
    elif (row['traffic_source'] == 'paid') & (row['region'] != 'Russia'):
        return 'other'
    elif (row['traffic_source'] == 'email') & (row['region'] != 'Russia'):
        return 'other'
    else:
        return row['traffic_source']
    
    

logs['source_type'] = logs.apply(source_type_func, axis = 1)

In [4]:
logs.query('traffic_source == "email"')

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
9,1549980765,3e7077fd2f,https://host.ru/df646c3676cc259fa0,Russia,6f9de8c8b6,email,ad
20,1549980816,de47c9b27e,https://host.ru/8fe7c39e5c598bbc54,Ukraine,2f25b6e26a,email,other
23,1549980839,015275e61f,https://host.ru/c8d9213a31839f9a3a,Russia,21bdc57777,email,ad
27,1549980853,ea49aa9f6f,https://host.ru/1afc5618562365020a,Russia,20e8e91ecf,email,ad
33,1549980897,7f9c9e31ac,https://host.ru/ac2d98a5a63e7c6e28,Belarus,38f45e7f9b,email,other
...,...,...,...,...,...,...,...
18904,1550094129,db3ed9712d,https://host.ru/186c4d6b47dbde0e74,Russia,6a670538ac,email,ad
18905,1550094130,0f83f523bd,https://host.ru/c8d9213a31839f9a3a,Russia,f0ad6c3a39,email,ad
18921,1550094218,b9723ef95e,https://host.ru/c8d9213a31839f9a3a,Ukraine,6d616e3a35,email,other
18923,1550094221,42af1bbaa1,https://host.ru/6fda01ec57f23abc9e,Russia,a15d5f2ad9,email,ad
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email,ad

# Задание 2
В файле URLs.txt содержатся url страниц новостного сайта. Вам необходимо отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. Выполните следующие действия:

Прочитайте содержимое файла с датафрейм
Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствии с заданным шаблоном

In [5]:
urls = pd.read_csv('/Users/maksim/Netology/material/URLs.txt')
import re

In [22]:
urls['result'] = urls['url'].str.contains(pat = '[/]\d{8}[-]', regex = True)
urls.query('result == True').sort_values('url')

                                                  url  result
84  /articles/36066499-iz-za-zvaniy-anny-netrebko-...    True
75  /articles/36082911-pribaltika-i-ukraina-v-pani...    True
81  /articles/36093326-shturmovat-donetsk-i-lugans...    True
60  /articles/36142564-ukrainu-ureguliruyut-po-tih...    True
69  /articles/36170146-rossiya-reshila-postavlyat-...    True
..                                                ...     ...
22  /world/36075956-na-granitse-s-krymom-zahvachen...    True
92  /world/36103095-dominikanskih-zhurnalistov-ubi...    True
64  /world/36195262-deputat-savchenko-predlozhila-...    True
49  /world/36206871-na-ukraine-nachalsya-shturm-uc...    True
83  /world/36215106-lider-ig-obratilsya-k-boevikam...    True

[84 rows x 2 columns]

# Домашнее задание 3
В датафрейме data создайте столбец lemmas, в котором вычислите леммы поисковых запросов из столбца keyword. Леммы должны иметь строковый тип.

In [13]:
from pymystem3 import Mystem
data = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})
data

                 keyword   shows
0    курс гривны к рублю  125076
1        доллары в рубли  114173
2  100 долларов в рублях   97534
3             курс рубля   53546

In [15]:
def lem (strok):
    m = Mystem()
    lemmas = m.lemmatize(strok)
    l = ' '.join(lemmas)
    return l
    

data['lemmas'] = data['keyword'].apply(lem)
data.head()

                 keyword   shows                        lemmas
0    курс гривны к рублю  125076  курс   гривна   к   рубль \n
1        доллары в рубли  114173         доллар   в   рубль \n
2  100 долларов в рублях   97534   100   доллар   в   рубль \n
3             курс рубля   53546               курс   рубль \n