In [8]:
import pandas as pd

# Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [3]:
ratings = pd.read_csv('/Users/maksim/Netology/material/ml-latest-small/ratings.csv')
movies = pd.read_csv('/Users/maksim/Netology/material/ml-latest-small/movies.csv')

In [56]:
movies_5 = ratings.query('rating == 5.0')
movies_5['movieId'].value_counts().head()

318     153
296     123
356     116
2571    109
260     104
Name: movieId, dtype: int64

In [58]:
movies.query('movieId == 318')

     movieId                             title       genres
277      318  Shawshank Redemption, The (1994)  Crime|Drama

# Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [9]:
data = pd.read_csv('/Users/maksim/Netology/material/ml-latest-small/power.csv')
data.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [38]:
filtered_countries = data[ ((data['country']=='Lithuania') | (data['country']=='Latvia') | (data['country']=='Estonia'))
                          & ((data["category"] == 4) | (data["category"] == 12) | (data["category"] == 21)) 
                          & (data["year"] >= 2005) & (data["year"] <= 2010)
                          & (data["quantity"] >= 0) 
                         ]                        
                        
#data[ data['country'].str.contains('lit', case=False) ]['country'].unique()
filtered_countries.head()
#count_quantity 
filtered_countries['quantity'].sum()

240580.0

# Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [45]:
page_url = 'https://www.finanz.ru/aktsii/realnom-vremeni-spisok/dow_jones'
df = pd.read_html(page_url, attrs = {'class': 'quote_list'}, encoding='utf-8')
#type(df)
table = df[0]
#type(table)
table

,Unnamed: 0,"Имя function __handleSortingClick(componentName, fieldName, sortOrder) { $.ajax({ url: ""/Ajax/IndexShareListForRealtime/Dow_Jones"", type: ""post"", data: ""orderBy="" + componentName + "":"" + fieldName + "":"" + sortOrder, success: function (v, x) { $('#index-list-container').html(v); try { trackPI(); } catch (e) { } }, error: function () { } }); }",ISIN,Пред. закр.,Посл. зн.,Объём,%,+/-,Время
0,NaN,3M,US88579Y1010,17052,17189,0,"0,80 %",137,18:04:33
1,NaN,American Express,US0258161092,11993,12002,0,"0,08 %",9,18:04:28
2,NaN,Amgen,US0311621009,22508,22803,0,"1,31 %",295,18:04:42
3,NaN,Apple,US0378331005,12272,12199,0,"-0,59 %",-73,18:04:45
4,NaN,Boeing,US0970231058,21301,21928,0,"2,94 %",627,18:04:45
5,NaN,Caterpillar,US1491231015,17326,17284,0,"-0,24 %",-42,18:04:40
6,NaN,Chevron,US1667641005,8745,8935,0,"2,17 %",190,18:04:44
7,NaN,Cisco,US17275R1023,4354,4362,0,"0,18 %",8,18:04:44
8,NaN,Coca-Cola,US1912161007,5204,5200,0,"-0,08 %",-4,18:04:36
9,NaN,Dow,US2605571031,5353,5300,0,"-0,99 %",-53,18:03:51
10,NaN,Goldman Sachs,US38141G1040,23208,23520,0,"1,34 %",312,18:03:56
11,NaN,Home Depot,US4370761029,27660,26995,0,"-2,40 %",-665,18:04:39
12,NaN,Honeywell,US4385161066,20620,20730,0,"0,53 %",110,18:04:36
13,NaN,IBM,US4592001014,12316,12375,0,"0,48 %",59,18:04:25
14,NaN,Intel,US4581401001,4956,4951,0,"-0,11 %",-6,18:04:45
15,NaN,Johnson & Johnson,US4781601046,14745,14886,0,"0,96 %",141,18:04:39
16,NaN,JPMorgan Chase &,US46625H1005,11974,12101,0,"1,06 %",127,18:04:41
17,NaN,McDonalds,US5801351017,21614,21227,0,"-1,79 %",-387,18:04:35
18,NaN,Merck,US58933Y1055,8155,8187,0,"0,39 %",32,18:04:34
19,NaN,Microsoft,US5949181045,21621,21339,0,"-1,30 %",-282,18:04:45
20,NaN,Nike,US6541061031,13544,13541,0,"-0,02 %",-3,18:04:35
21,NaN,Procter & Gamble,US7427181091,13937,13957,0,"0,14 %",20,18:04:24
22,NaN,Salesforce,US79466L3024,24135,21965,0,"-8,99 %",-2170,18:04:44
23,NaN,Travelers,US89417E1091,13341,13344,0,"0,02 %",3,18:04:16
24,NaN,UnitedHealth,US91324P1021,34119,34593,0,"1,39 %",474,18:04:26
25,NaN,Verizon,US92343V1044,6058,6153,0,"1,56 %",95,18:04:45
26,NaN,Visa,US92826C8394,21120,21096,0,"-0,11 %",-24,18:04:41
27,NaN,Walgreens Boots Alliance,US9314271084,3846,3880,0,"0,88 %",34,18:04:32
28,NaN,Walmart,US9311421039,15264,15136,0,"-0,84 %",-128,18:04:37
29,NaN,Walt Disney,US2546871060,14944,15036,0,"0,62 %",92,18:04:35